version: "3"
services:
  freecad:
    image: lscr.io/linuxserver/freecad:latest
    container_name: freecad
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghi
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=fonts-noto-cjk
      - LC_ALL=zh_CN.UTF-8
    volumes:
      - ./config:/config #自定义存储路径
    ports:
      - 3000:3000 #自定义HTTP端口
      - 3001:3001 #自定义HTTPS端口，不用可删除
    restart: always