version: "3"
networks:
  dllcnx:
    external: true
services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
    volumes:
      - /tmp/zfsv3/sata11/xxxxx/data/docker/jackett/config:/config #配置路径
      - /tmp/zfsv3/sata11/xxxx/data/docker/jackett/downloads:/downloads #下载路径
    ports:
      - 9117:9117
    restart: unless-stopped
