version: '3.3'
services:
    alist:
        image: 'xhofe/alist:latest'
        container_name: alist
        # /etc/alist是映射到本机的存储路径，可以修改
        volumes:
            - '/tmp/zfsv3/sata11/xxxx/data/docker/alist/data:/opt/alist/data'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
